export const TZ_TEMPLATE = {
  year_month_day: "YYYY/MM/DD",
  year_month: "YYYY-MM",
  month_day: "MM/DD",
  month_day_v2: "M/D",
  month_day_hour: "M/D HH:mm",
  hour: "HH:mm",
  hour_v2: "HH:mm:ss",
  month: "MM",
  day: "DD",
  second: "mm:ss",
  second_v2: "mmss",
  jp_day: "(ddd)",
  year: "YYYY",
  year_month_day_v2: "YYYY MM/DD",
  year_month_day_v3: "YYYY-MM-DD",
  year_month_day_v4: "YYYY/MM/DD HH:mm",
  short_month: "M",
  short_day: "D",
  date_utc: "YYYY-MM-DDTHH:mm:ss",
  year_month_day_v5: "YYYY/MM/DD(ddd)",
  year_month_day_v6: "YYYY/MM/DD HH:mm:ss",
  date_day_month: "dddd, DD MMM",
};
